[package]
name = "bevy-osm-tiles"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.1", optional = true }
tracing = "0.1.41"

[dev-dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
clap = { version = "4.0", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[example]]
name = "cli_city_loader"
path = "examples/cli_city_loader.rs"
required-features = ["cli"]

[features]
default = []
bevy = ["dep:bevy"]
cli = []
